[package]
name = "TrainTracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
reqwest = "0.12.24"
serde = "1.0.188"
thiserror = "2.0.17"
url = "2.5.7"

[dependencies.mongodb]
version = "3.4.1"
features = ["sync"]
